name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/waterlemons2k/linux-deps:buster
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: torvalds/linux
          ref: v3.18

      - run: |
          make defconfig

          echo "DATE=$(date +%F)" >> "$GITHUB_ENV"

      - name: Build
        run: make -j$(nproc) LOCALVERSION= deb-pkg

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATE }}
          files: ../*.deb
