name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/waterlemons2k/linux-deps:jessie
    steps:
      - name: Checkout
        run: git clone --depth=1 -b v3.18 https://github.com/torvalds/linux.git .

      - run: |
          make ARCH=arm olddefconfig oldconfig

          echo "DATE=$(date +%F)" >> "$GITHUB_ENV"

      - name: Build
        run: make -j$(nproc) ARCH=arm LOCALVERSION= deb-pkg

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATE }}
          files: ../*.deb
