name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/waterlemons2k/linux-deps:jessie
    steps:
      - name: Setup toolchain
        working-directory: /opt
        run: |
          curl -LO https://releases.linaro.org/archive/14.05/components/toolchain/binaries/gcc-linaro-4.9-2014.05-arm-linux-gnueabihf-x86_64-linux-gnu.tar.xz
          tar xf *.xz
          rm *.xz
      - name: Checkout Linux
        run: |
          curl -O https://www.kernel.org/pub/linux/kernel/v3.x/linux-3.18.24.tar.xz
          tar xf linux-3.18.24.tar.xz --strip-components 1

      - run: |
          make ARCH=arm multi_v7_defconfig oldconfig

          echo "DATE=$(date +%F)" >> "$GITHUB_ENV"

      - name: Build
        run: |
          export PATH="$PATH:/opt/gcc-linaro-4.9-2014.05-arm-linux-gnueabihf-x86_64-linux-gnu/bin"
          make -j$(nproc) ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- LOCALVERSION= deb-pkg

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          apt-get update
          apt-get install -y --allow-unauthenticated apt-transport-https
          echo "deb https://cli.github.com/packages stable main" >/etc/apt/sources.list.d/github-cli.list
          apt-get update
          apt-get install -y --allow-unauthenticated gh

          gh release create -R ${{ github.repository }} ${{ env.DATE }} ../*.deb
